# Generated by Django 3.0.1 on 2021-03-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC')], max_length=1)),
                ('text', models.TextField(default='')),
                ('shopify_location_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier', models.CharField(choices=[('U', 'Unit'), ('W', 'White'), ('Y', 'Yellow'), ('R', 'Red'), ('O', 'Orange'), ('B', 'Blue'), ('G', 'Green'), ('L', 'Lavender')], max_length=1)),
                ('code', models.CharField(max_length=3)),
                ('shopify_handle', models.CharField(max_length=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.ProductType'),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.Variant')),
            ],
        ),
    ]
