# Generated by Django 3.0.1 on 2021-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20210315_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricing',
            name='shopify_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='staff_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_handle',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
