# Generated by Django 3.0.1 on 2021-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20210321_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
