# Generated by Django 3.0.1 on 2021-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_variant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
