# Generated by Django 3.0.1 on 2021-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20210321_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
