# Generated by Django 3.0.1 on 2021-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20210404_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
