# Generated by Django 3.0.1 on 2021-06-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_producttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700')], max_length=1, unique=True),
        ),
    ]
