# Generated by Django 3.0.1 on 2021-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20210629_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('Q', 'Quick Links'), ('A', 'Active Guides'), ('C', 'Communications'), ('E', 'External Resources')], max_length=1)),
                ('link_style', models.CharField(max_length=64)),
            ],
        ),
    ]
