# Generated by Django 3.0.1 on 2021-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_handle',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
