# Generated by Django 3.0.1 on 2022-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_auto_20211020_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700'), ('X', 'ALL'), ('D', 'DOT')], max_length=1, unique=True),
        ),
    ]
