# Generated by Django 3.0.1 on 2022-03-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_auto_20220127_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
