# Generated by Django 3.0.1 on 2019-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ddo_hourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hDate', models.DateField()),
                ('h08', models.IntegerField()),
                ('h09', models.IntegerField()),
                ('h10', models.IntegerField()),
                ('h11', models.IntegerField()),
                ('h12', models.IntegerField()),
                ('h13', models.IntegerField()),
                ('h14', models.IntegerField()),
                ('h15', models.IntegerField()),
                ('h16', models.IntegerField()),
                ('h17', models.IntegerField()),
                ('h18', models.IntegerField()),
                ('h19', models.IntegerField()),
                ('hTotal', models.IntegerField(default=-1)),
            ],
        ),
    ]
