# Generated by Django 3.0.1 on 2019-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpandedMaterialMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eName', models.CharField(max_length=128)),
                ('eDate', models.DateField()),
                ('eMode', models.CharField(max_length=128)),
                ('eTrips', models.CharField(max_length=128)),
                ('eOrigin', models.CharField(max_length=128)),
                ('eOriginLocation', models.CharField(max_length=128)),
                ('eDestination', models.CharField(max_length=128)),
                ('eDestinationLocation', models.CharField(max_length=128)),
                ('eTimestamp', models.CharField(max_length=128)),
                ('eMaterial', models.CharField(max_length=128)),
                ('ePallets', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('eTripID', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rName', models.CharField(max_length=128)),
                ('rDate', models.DateField()),
                ('rMode', models.CharField(max_length=128)),
                ('rTrips', models.CharField(max_length=128)),
                ('rOrigin', models.CharField(max_length=128)),
                ('rOriginLocation', models.CharField(max_length=128)),
                ('rDestination', models.CharField(max_length=128)),
                ('rDestinationLocation', models.CharField(max_length=128)),
                ('rMaterial', models.CharField(max_length=2048)),
                ('rHidden', models.CharField(max_length=1024)),
                ('rTimestamp', models.CharField(max_length=128)),
            ],
        ),
    ]
