# Generated by Django 2.2.5 on 2019-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rName', models.CharField(max_length=128)),
                ('rDate', models.DateField()),
                ('rMode', models.CharField(max_length=128)),
                ('rTips', models.CharField(max_length=128)),
                ('rOrigin', models.CharField(max_length=128)),
                ('rOriginLocation', models.CharField(max_length=128)),
                ('rDestination', models.CharField(max_length=128)),
                ('rDestinationLocation', models.CharField(max_length=128)),
                ('rMaterial', models.CharField(max_length=2048)),
                ('rHidden', models.CharField(max_length=1024)),
                ('rTimestamp', models.CharField(max_length=128)),
            ],
        ),
    ]
