# Generated by Django 2.2.5 on 2019-11-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp1', models.CharField(max_length=128)),
                ('temp2', models.CharField(max_length=128)),
            ],
        ),
    ]
