# Generated by Django 3.0.1 on 2021-07-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20210629_2328'),
        ('mm', '0002_movement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mm.Movement')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.ProductType')),
            ],
        ),
    ]
