# Generated by Django 3.0.1 on 2021-07-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20210629_2328'),
        ('mm', '0003_auto_20210723_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pallets',
            new_name='Pallet',
        ),
    ]
