# Generated by Django 2.2.5 on 2019-11-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_testclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
