# Generated by Django 3.0.1 on 2022-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_auto_20210723_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='destination_location',
            field=models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700'), ('D', 'DOT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movement',
            name='origin_location',
            field=models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700'), ('D', 'DOT')], max_length=1),
        ),
    ]
