# Generated by Django 2.2.5 on 2019-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0005_delete_testclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialmovement',
            old_name='rTips',
            new_name='rTrips',
        ),
    ]
