# Generated by Django 2.2.5 on 2019-11-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0006_auto_20191106_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpandedMaterialMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eName', models.CharField(max_length=128)),
                ('eDate', models.DateField()),
                ('eMode', models.CharField(max_length=128)),
                ('eTrips', models.CharField(max_length=128)),
                ('eOrigin', models.CharField(max_length=128)),
                ('eOriginLocation', models.CharField(max_length=128)),
                ('eDestination', models.CharField(max_length=128)),
                ('eDestinationLocation', models.CharField(max_length=128)),
                ('eTimestamp', models.CharField(max_length=128)),
                ('eMaterial', models.CharField(max_length=128)),
                ('ePallets', models.CharField(max_length=128)),
                ('eTripID', models.CharField(max_length=128)),
            ],
        ),
    ]
