# Generated by Django 2.2.5 on 2019-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0007_expandedmaterialmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandedmaterialmovement',
            name='ePallets',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
