# Generated by Django 2.2.5 on 2019-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0008_auto_20191212_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandedmaterialmovement',
            name='ePallets',
            field=models.CharField(max_length=128),
        ),
    ]
