# Generated by Django 2.2.5 on 2019-12-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0009_auto_20191212_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expandedmaterialmovement',
            old_name='ePallets',
            new_name='ePalletsX',
        ),
    ]
