# Generated by Django 2.2.5 on 2019-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0010_auto_20191212_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandedmaterialmovement',
            name='ePallets',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
