# Generated by Django 2.2.5 on 2019-12-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0011_expandedmaterialmovement_epallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandedmaterialmovement',
            name='ePalletsX',
        ),
    ]
