# Generated by Django 3.0.1 on 2021-06-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0011_auto_20210629_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('D', 'Donations'), ('O', 'Overflow'), ('P', 'Processing'), ('S', 'Salesfloor')], max_length=1)),
                ('destination', models.CharField(choices=[('D', 'Donations'), ('O', 'Overflow'), ('P', 'Processing'), ('S', 'Salesfloor')], max_length=1)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('staff_id', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origin_location', models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700')], max_length=1)),
                ('destination_location', models.CharField(choices=[('I', 'IRC'), ('T', 'TRMC'), ('7', '700')], max_length=1)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.ProductType')),
            ],
        ),
    ]
