# Generated by Django 3.0.1 on 2021-07-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
