# Generated by Django 3.0.1 on 2020-05-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AceInventory',
            fields=[
                ('Index', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemCode', models.CharField(max_length=64)),
                ('Location', models.CharField(max_length=64)),
                ('Department', models.CharField(max_length=64)),
                ('Upc', models.CharField(max_length=64)),
                ('Qoh', models.IntegerField()),
                ('Mpn', models.CharField(max_length=64)),
                ('Retail', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Status', models.CharField(max_length=64)),
            ],
        ),
    ]
