# Generated by Django 3.0.1 on 2020-05-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceinventory',
            name='Index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aceinventory',
            name='ItemCode',
            field=models.CharField(max_length=64),
        ),
    ]
