# Generated by Django 3.0.1 on 2020-07-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial_manual2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('handle', models.CharField(max_length=128)),
                ('barcode', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('option1', models.CharField(max_length=128)),
                ('product_id', models.CharField(max_length=128)),
                ('variant_id', models.CharField(max_length=128)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('inventory_item_id', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=128)),
                ('sku', models.CharField(max_length=128)),
                ('body_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('handle', models.CharField(max_length=128)),
                ('barcode', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('option1', models.CharField(max_length=128)),
                ('product_id', models.CharField(max_length=128)),
                ('variant_id', models.CharField(max_length=128)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('inventory_item_id', models.CharField(max_length=128)),
                ('product_type', models.CharField(max_length=128)),
                ('vendor', models.CharField(max_length=128)),
                ('sku', models.CharField(max_length=128)),
                ('staff', models.CharField(max_length=128)),
                ('meta', models.TextField()),
                ('location_id', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
