# Generated by Django 3.0.1 on 2020-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_inventorylookup_inventorymovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylookup',
            name='body_html',
            field=models.TextField(default=''),
        ),
    ]
