# Generated by Django 3.0.1 on 2020-08-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('flr_email', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
                ('location', models.CharField(max_length=64)),
            ],
        ),
    ]
