# Generated by Django 3.0.1 on 2021-02-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='capacity',
            field=models.FloatField(null=True),
        ),
    ]
