# Generated by Django 3.0.1 on 2022-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitors_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='flr_email',
        ),
    ]
