# Generated by Django 3.0.1 on 2021-04-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('phone', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=256)),
                ('giftcard', models.CharField(default='', max_length=256)),
                ('initial_balance', models.DecimalField(decimal_places=2, default='0.0', max_digits=6)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('giftcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qbgiftcard.GiftCard')),
            ],
        ),
    ]
