# Generated by Django 3.0.1 on 2021-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbgiftcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('i', 'initial'), ('q', 'qbgiftcard'), ('u', 'upgraded'), ('r', 'remap')], default='i', max_length=1),
        ),
    ]
