# Generated by Django 3.0.1 on 2021-04-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbgiftcard', '0002_giftcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
