# Generated by Django 3.0.1 on 2021-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbgiftcard', '0003_auto_20210410_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='LINK',
            field=models.CharField(default='', max_length=129),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='UID',
            field=models.IntegerField(default=-1),
        ),
    ]
